services:
  node:
    build: 
      context: ./node
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/nodejsnginx
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    restart: always
    networks:
      - app-network
   
  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - node
    restart: always
    networks:
      - app-network

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nodejsnginx
    ports:
      - 5444:5432
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

networks:
    app-network:
      driver: bridge